version: '2.1'
services:
  rabbitmq:
    image: "rabbitmq:3.6.5-management"
    hostname: "rabbitmq"
    volumes:
      - ./run/config/rabbitmq/definitions.json:/opt/definitions.json:ro
      - ./run/config/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    ports:
      - "15672:15672"
      - "5672:5672"

  stressrabbit:
    build: ./test/stress_rabbit
    hostname: stressrabbit
    container_name: stressrabbit
    depends_on:
      - rabbitmq
